//! Schema negotiation types for the v7 wire protocol.
//!
//! These types support schema-level negotiation between source and
//! destination plugins, enabling field-level constraint checking and
//! rich schema metadata exchange.

use serde::{Deserialize, Serialize};

// ── Field Constraint ───────────────────────────────────────────────

/// Constraint level for a field during schema negotiation.
///
/// Destinations use this to communicate per-field requirements back
/// to sources or the orchestrator during schema validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldConstraint {
    /// The field is required and must be present.
    FieldRequired,
    /// The field is optional and may be omitted.
    FieldOptional,
    /// The field must not be present.
    FieldForbidden,
    /// The field is recommended but not strictly required.
    FieldRecommended,
    /// The field's type is incompatible with the destination.
    TypeIncompatible,
}

// ── Field Requirement ──────────────────────────────────────────────

/// A single field-level requirement emitted during schema negotiation.
///
/// Pairs a [`FieldConstraint`] with a human-readable reason and an
/// optional list of accepted Arrow type names.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FieldRequirement {
    /// Name of the field this requirement applies to.
    pub field_name: String,
    /// The constraint level for this field.
    pub constraint: FieldConstraint,
    /// Human-readable explanation of why the constraint exists.
    pub reason: String,
    /// Arrow type names the destination can accept for this field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accepted_types: Option<Vec<String>>,
}

// ── Schema Field ───────────────────────────────────────────────────

/// A single field in a [`StreamSchema`].
///
/// Describes the field's Arrow type, nullability, and role within the
/// stream (primary key, generated, partition key).
#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SchemaField {
    /// Column name.
    pub name: String,
    /// Canonical Arrow type name (e.g., `"int64"`, `"utf8"`).
    pub arrow_type: String,
    /// Whether the field permits null values.
    pub nullable: bool,
    /// Whether this field is part of the primary key.
    #[serde(default)]
    pub is_primary_key: bool,
    /// Whether this field is generated by the source (e.g., auto-increment).
    #[serde(default)]
    pub is_generated: bool,
    /// Whether this field is used as a partition key.
    #[serde(default)]
    pub is_partition_key: bool,
    /// Default value expression for this field, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
}

impl SchemaField {
    /// Create a new schema field with the given name, Arrow type, and nullability.
    #[must_use]
    pub fn new(name: impl Into<String>, arrow_type: impl Into<String>, nullable: bool) -> Self {
        Self {
            name: name.into(),
            arrow_type: arrow_type.into(),
            nullable,
            is_primary_key: false,
            is_generated: false,
            is_partition_key: false,
            default_value: None,
        }
    }

    /// Mark this field as a primary key (or not).
    #[must_use]
    pub fn with_primary_key(mut self, is_primary_key: bool) -> Self {
        self.is_primary_key = is_primary_key;
        self
    }

    /// Mark this field as generated (or not).
    #[must_use]
    pub fn with_generated(mut self, is_generated: bool) -> Self {
        self.is_generated = is_generated;
        self
    }
}

// ── Stream Schema ──────────────────────────────────────────────────

/// Full schema definition for a stream, including field metadata and keys.
///
/// Used during v7 schema negotiation to exchange rich schema information
/// between source, transform, and destination plugins.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct StreamSchema {
    /// Ordered list of fields in this stream.
    pub fields: Vec<SchemaField>,
    /// Column names that form the primary key.
    #[serde(default)]
    pub primary_key: Vec<String>,
    /// Column names used for partitioning.
    #[serde(default)]
    pub partition_keys: Vec<String>,
    /// Source-defined cursor column for incremental sync.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_defined_cursor: Option<String>,
    /// Opaque schema identifier for change detection across runs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema_id: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_field_roundtrip() {
        let field = SchemaField::new("user_id", "int64", false).with_primary_key(true);
        let json = serde_json::to_string(&field).unwrap();
        let back: SchemaField = serde_json::from_str(&json).unwrap();
        assert_eq!(field, back);
    }

    #[test]
    fn stream_schema_with_primary_key() {
        let schema = StreamSchema {
            fields: vec![
                SchemaField::new("id", "int64", false).with_primary_key(true),
                SchemaField::new("name", "utf8", true),
            ],
            primary_key: vec!["id".into()],
            partition_keys: vec![],
            source_defined_cursor: None,
            schema_id: None,
        };
        assert_eq!(schema.fields.len(), 2);
        assert_eq!(schema.primary_key, vec!["id"]);
        assert!(schema.fields[0].is_primary_key);
        assert!(!schema.fields[1].is_primary_key);
    }

    #[test]
    fn field_constraint_serde() {
        let constraint = FieldConstraint::FieldRequired;
        let json = serde_json::to_string(&constraint).unwrap();
        assert_eq!(json, "\"field_required\"");
    }

    #[test]
    fn field_requirement_roundtrip() {
        let req = FieldRequirement {
            field_name: "email".into(),
            constraint: FieldConstraint::FieldRequired,
            reason: "destination requires email for dedup".into(),
            accepted_types: None,
        };
        let json = serde_json::to_string(&req).unwrap();
        let back: FieldRequirement = serde_json::from_str(&json).unwrap();
        assert_eq!(req, back);
    }

    #[test]
    fn field_requirement_with_accepted_types() {
        let req = FieldRequirement {
            field_name: "age".into(),
            constraint: FieldConstraint::TypeIncompatible,
            reason: "float not supported, use integer".into(),
            accepted_types: Some(vec!["int32".into(), "int64".into()]),
        };
        let json = serde_json::to_value(&req).unwrap();
        let types = json["accepted_types"].as_array().unwrap();
        assert_eq!(types.len(), 2);
        assert_eq!(types[0], "int32");
        assert_eq!(types[1], "int64");
    }

    #[test]
    fn schema_field_builder_chain() {
        let field = SchemaField::new("id", "int64", false)
            .with_primary_key(true)
            .with_generated(true);
        assert!(field.is_primary_key);
        assert!(field.is_generated);
        assert!(!field.nullable);
        assert_eq!(field.name, "id");
        assert_eq!(field.arrow_type, "int64");
    }
}
